// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pindorama_Backend.Context;

#nullable disable

namespace Pindorama_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pindorama_Backend.Models.Passagem", b =>
                {
                    b.Property<int>("PassagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Assento")
                        .HasColumnType("int");

                    b.Property<string>("CidadeDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CidadeOrigem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Embarque")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumeroBilhete")
                        .HasColumnType("int");

                    b.Property<int>("Portao")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Terminal")
                        .HasColumnType("int");

                    b.HasKey("PassagemId");

                    b.ToTable("Passagens");
                });
#pragma warning restore 612, 618
        }
    }
}
